### ISSUE TITLE
[In-app report] Triggered error boundary

### ISSUE THREAD

**Issue by GukOnDiscord** [dumpus-app/dumpus-app#313]
## Error

```bash
Version: v1.0.0-web (prod)
Name: TypeError
Message: Cannot read property 'replace' of null
Cause: none
Stack: TypeError: Cannot read property 'replace' of null
    at https://web.dumpus.app/_next/static/chunks/app/%5Blocale%5D/(app)/layout-ea4f787ef001c1a5.js:1:209400
    at nk (https://web.dumpus.app/_next/static/chunks/app/%5Blocale%5D/(app)/layout-ea4f787ef001c1a5.js:1:209951)
    at ri (https://web.dumpus.app/_next/static/chunks/a6a31439-e10e70cfb2480d3c.js:9:38933)
    at lp (https://web.dumpus.app/_next/static/chunks/a6a31439-e10e70cfb2480d3c.js:9:54224)
    at im (https://web.dumpus.app/_next/static/chunks/a6a31439-e10e70cfb2480d3c.js:9:112409)
    at oM (https://web.dumpus.app/_next/static/chunks/a6a31439-e10e70cfb2480d3c.js:9:90100)
    at https://web.dumpus.app/_next/static/chunks/a6a31439-e10e70cfb2480d3c.js:9:89922
    at oT (https://web.dumpus.app/_next/static/chunks/a6a31439-e10e70cfb2480d3c.js:9:89929)
    at ov (https://web.dumpus.app/_next/static/chunks/a6a31439-e10e70cfb2480d3c.js:9:87567)
    at nG (https://web.dumpus.app/_next/static/chunks/a6a31439-e10e70cfb2480d3c.js:9:36834)
```

## Infos

- Location: https://web.dumpus.app/en/overview/
- Platform: web

**Comment by florian-lefebvre** [comment]
So you went through the onboarding without any issue right?

Can you give me your OS version + browser?

**Comment by GukOnDiscord** [comment]
> So you went through the onboarding without any issue right? Yes
> 
> Can you give me your OS version + browser? Chrome (i forgot version, the bug is same in app too

**Comment by florian-lefebvre** [comment]
@GukOnDiscord ?

**Comment by florian-lefebvre** [comment]
My bad, didn't see you added them in the quote. Thank you!
